- name: Validate connection
  hosts: raspberry_pi
  become: yes

  tasks:
  - name: Get host info
    debug:
      msg:
        - "My hostname is {{ ansible_hostname }}"
        - "My home is {{ ansible_env.HOME }}"
